### ISSUE TITLE
Unused tutorial portion?

### ISSUE THREAD

**Issue by psokolhessner** [sokolhessnerlab/resources#2]
**Describe the bug**
Under the `Git` subsection of `Resources`, there is a "Tutorial" link. The link is broken in the TOC, and the tutorial heading down in the readme.md text ("Git Tutorial Emoji") is redundant with "GitHub Tutorial: Emoji" further down. 

**To Reproduce**
1. Go to https://github.com/sokolhessnerlab/resources#table-of-contents
2. click "Tutorial" under "Git" (link is https://github.com/sokolhessnerlab/resources#git_tutorial). Nothing happens. The relevant section (link: https://github.com/sokolhessnerlab/resources#git-tutorial-emoji) is also empty.

**Expected behavior**
There should be only one tutorial on emoji, and clicking the link to the singular emoji tutorial in the TOC should take you there. This should probably be removed. 

**Screenshot**
See screenshot:
![Screen Shot 2020-04-20 at 8 17 03 AM](https://user-images.githubusercontent.com/24814952/79761984-60b4c900-82df-11ea-8bdc-a5cbf31f1e80.png)

**Comment by aridyckovsky** [comment]
Thanks for pointing this out. The issue should now be resolved. Closing this issue.
